# Generated by Django 6.1.1 on 2026-09-04 13:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название дисциплины')),
                ('semester', models.PositiveSmallIntegerField(verbose_name='Семестр')),
                ('lecturer', models.CharField(blank=True, max_length=150, verbose_name='Преподаватель')),
                ('faculty', models.CharField(max_length=150, verbose_name='Факультет/Кафедра')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ST', 'Студент'), ('SR', 'Староста'), ('MD', 'Модератор')], default='ST', max_length=2, verbose_name='Роль в системе')),
                ('university', models.CharField(blank=True, max_length=150, verbose_name='Вуз')),
                ('faculty', models.CharField(blank=True, max_length=150, verbose_name='Факультет')),
                ('course', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Курс')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок материала')),
                ('description', models.TextField(blank=True, verbose_name='Описание контента')),
                ('material_type', models.CharField(choices=[('LEC', 'Лекция'), ('PRC', 'Практика/Семинар'), ('LAB', 'Лабораторная работа'), ('EXM', 'Материалы к экзамену'), ('LNK', 'Полезная ссылка')], default='LEC', max_length=3, verbose_name='Тип материала')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='materials/%Y/%m/', verbose_name='Файл')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний/переходов')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверено модератором')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='studhub_core.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Учебный материал',
                'verbose_name_plural': 'Учебные материалы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_upvote', models.BooleanField(verbose_name='Положительная оценка (Лайк)')),
                ('report_reason', models.TextField(blank=True, null=True, verbose_name='Жалоба на неактуальность/спам')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='studhub_core.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка материала',
                'verbose_name_plural': 'Оценки материалов',
                'unique_together': {('material', 'user')},
            },
        ),
    ]
